const SHOW_CART = "SHOW_CART";
const SHOW_MENU = "SHOW_MENU";
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const REDUCE_CART_ITEM = "REDUCE_CART_ITEM";
const ADD_TO_CART_ = "ADD_TO_CART_";
export {
  SHOW_CART,
  SHOW_MENU,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  REDUCE_CART_ITEM,
  ADD_TO_CART_,
};
